In [21]:
!pip install gym==0.17.3

In [22]:
import gym
entorno= gym.make('FrozenLake-v0')

In [23]:
#método render se visualiza el entorno y su estado actual
entorno.render()


SFFF
FHFH
FFFH
HFFG


In [24]:
#observation_space para el espacio de estados
S = entorno.observation_space
print(S)

Discrete(16)


In [25]:
#action_space contiene el espacio de acciones
A = entorno.action_space
print(A)

Discrete(4)


In [26]:
#P la funcion de transicion, undisscionario que tiene el mismo tamaño que elnumero de estado
P = entorno.P
print('Función de transición', P)
print('Longitud de P:', len(P))

Función de transición {0: {0: [(0.3333333333333333, 0, 0.0, False), (0.3333333333333333, 0, 0.0, False), (0.3333333333333333, 4, 0.0, False)], 1: [(0.3333333333333333, 0, 0.0, False), (0.3333333333333333, 4, 0.0, False), (0.3333333333333333, 1, 0.0, False)], 2: [(0.3333333333333333, 4, 0.0, False), (0.3333333333333333, 1, 0.0, False), (0.3333333333333333, 0, 0.0, False)], 3: [(0.3333333333333333, 1, 0.0, False), (0.3333333333333333, 0, 0.0, False), (0.3333333333333333, 0, 0.0, False)]}, 1: {0: [(0.3333333333333333, 1, 0.0, False), (0.3333333333333333, 0, 0.0, False), (0.3333333333333333, 5, 0.0, True)], 1: [(0.3333333333333333, 0, 0.0, False), (0.3333333333333333, 5, 0.0, True), (0.3333333333333333, 2, 0.0, False)], 2: [(0.3333333333333333, 5, 0.0, True), (0.3333333333333333, 2, 0.0, False), (0.3333333333333333, 1, 0.0, False)], 3: [(0.3333333333333333, 2, 0.0, False), (0.3333333333333333, 1, 0.0, False), (0.3333333333333333, 0, 0.0, False)]}, 2: {0: [(0.3333333333333333, 2, 0.0, False

In [27]:
#probabilidad de ese estado, estado siguuiente, recompensa, estado_terminal)
#P[desde este estado][tomando esta acción]
P[14][2]

[(0.3333333333333333, 14, 0.0, False),
 (0.3333333333333333, 15, 1.0, True),
 (0.3333333333333333, 10, 0.0, False)]

In [28]:
s = entorno.reset()
print(s)
entorno.render()

0

SFFF
FHFH
FFFH
HFFG


In [29]:
a = entorno.action_space.sample()
print(a)

3


In [30]:
sp, r, done, info = entorno.step(a)
print('Nuevo estado:', sp)
print('Recompensa:', r)
print('Termino el episodio:', done)
print('Información adicional:', info)

Nuevo estado: 0
Recompensa: 0.0
Termino el episodio: False
Información adicional: {'prob': 0.3333333333333333}


In [31]:
entorno.render()

  (Up)
SFFF
FHFH
FFFH
HFFG


In [32]:
entorno.reset()
entorno.render()


SFFF
FHFH
FFFH
HFFG


In [33]:
#Definir una politica (estrategia del agente pa llegar al objetivo final)
#aleatoria: la prob de llegar a la acción a partiendo del estado s: igual para las 4 acciones
import numpy as np
politica_al= np.ones([entorno.nS,entorno.nA])/entorno.nA
print(politica_al.shape)
print(politica_al)
#columnas son acciones y filas estados

(16, 4)
[[0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]]


In [34]:
#convolucional con tamaño de filtro X y la cantidad de nueronas que queramos y la estrcutura que queramos

In [82]:
#RNN Y LA OTRA SOLO PARA AUDIO
# SIPaKMed


evaluacion de la politica:

entrada: entorno, la politica (nSxnA), gamma, theta (crietrio de convergencia

salida: l funcion v(1xnS)

In [36]:
#constantes
GAMMA = 0.99
THETA = 1e-10

In [43]:
#algoritmo de la evaluación de la politica
def evaluacion_politica(entorno, politica, gamma=GAMMA, theta=THETA):
  V = np.zeros(entorno.nS)

  while True:
    delta = 0
    for s in range(entorno.nS):
      Vs= 0
      for a, pr in enumerate(politica[s]):
        for prob, state_, reward, done in entorno.P[s][a]:
          Vs += pr * prob * (reward + gamma * V[state_])
      delta = max(delta, np.abs(V[s]- Vs))
      V[s] = Vs

    if delta < theta: #si converge deteiene las iteraciones
      break

  return V

In [44]:
V_al = evaluacion_politica(entorno, politica_al)
print('Evaluacion de la politica aleatoria')
print(V_al.reshape(4,4))

Evaluacion de la politica aleatoria
[[0.01235614 0.01042446 0.01933844 0.00947775]
 [0.01478705 0.         0.03889445 0.        ]
 [0.03260247 0.08433764 0.13781085 0.        ]
 [0.         0.17034482 0.43357944 0.        ]]


Mejorar la politica:

entrada: entorno, politica, la funcionnde eestado de valor, gamma

Salida: q

In [48]:
def calcular_funcion_q(entorno, V, s, gamma=GAMMA):
  q = np.zeros(entorno.nA)
  for a in range(entorno.nA):
    for prob, state_, reward, done in entorno.P[s][a]:
      q[a] += prob*(reward + GAMMA * V[state_])
  return q

In [49]:
Q_al = np.zeros([entorno.nS, entorno.nA])

for s in range(entorno.nS):
  Q_al[s] = calcular_funcion_q(entorno, V_al, s)

print('Funcion accion-valor politica aleatoria')
print(Q_al)

Funcion accion-valor politica aleatoria
[[0.01303478 0.01239732 0.01239732 0.01159512]
 [0.0075176  0.01045921 0.00982176 0.01389928]
 [0.02265692 0.0194029  0.02234451 0.01294941]
 [0.00950934 0.00950934 0.00625531 0.012637  ]
 [0.01971607 0.01563854 0.01483634 0.00895725]
 [0.         0.         0.         0.        ]
 [0.05185927 0.04547758 0.05185927 0.00638168]
 [0.         0.         0.         0.        ]
 [0.01563854 0.03859024 0.03271115 0.04346997]
 [0.06697261 0.11245019 0.10169137 0.0562364 ]
 [0.18374781 0.17091264 0.15591638 0.04066659]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.08404521 0.19929501 0.22712643 0.17091264]
 [0.24477259 0.53262834 0.52189213 0.43502471]
 [0.         0.         0.         0.        ]]


In [50]:
def mejorar_politica(entorno, V, gamma=GAMMA):
  #se inicia con una politica arbitraria
  politica = np.zeros([entorno.nS, entorno.nA])

  #Y se mejora
  for s in range(entorno.nS):
    q = calcular_funcion_q(entorno, V, s, gamma)
    politica[s][np.argmax(q)] = 1
  return politica

In [52]:
politica_mejorada = mejorar_politica(entorno, V_al)
print('Politica Alearoria')
print(politica_al)
print('Evaluacion politica')
print(V_al)
print('Politica Mejorada')
print(politica_mejorada)

Politica Alearoria
[[0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]]
Evaluacion politica
[0.01235614 0.01042446 0.01933844 0.00947775 0.01478705 0.
 0.03889445 0.         0.03260247 0.08433764 0.13781085 0.
 0.         0.17034482 0.43357944 0.        ]
Politica Mejorada
[[1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]


Iteracion de la politica (obtener la politica optima)

entrada: entorno, gamma, theta

salida: politica optima (nSxnA)

In [53]:
def iterar_politica(entorno, gamma = GAMMA, theta=THETA):
  politica = np.ones([entorno.nS, entorno.nA])/entorno.nA
  while True:
    V = evaluacion_politica(entorno, politica)
    politica_nueva = mejorar_politica(entorno, V)
    if (politica_nueva == politica).all():
      break
    politica = np.copy(politica_nueva)
  return politica_nueva, V

In [55]:
politica_ite, V_ite = iterar_politica(entorno)
print('Politica Optima iteracion de la politica')
print(politica_ite)
print('Politica original')
print(politica_al)
print('Funcion estado valor - iteracion de la politica')
print(V_ite.reshape(4,4))
print('Funcion estado valor original')
print(V_al.reshape(4,4))

Politica Optima iteracion de la politica
[[1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]
Politica original
[[0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]]
Funcion estado valor - iteracion de la politica
[[0.54202593 0.49880319 0.47069569 0.4568517 ]
 [0.55845096 0.         0.35834807 0.        ]
 [0.59179874 0.64307982 0.61520756 0.        ]
 [0.         0.74172044 0.86283743 0.        ]]
Funcion estado valor original
[[0.01235614 0.01042446 0.01933844 0.00947775]
 [0.01478705 0.  

iteracion de valores (politica optima)

entrada: entorno, gamma, theta

salida: politica optima, funcion de estado valor (V)

In [58]:
def iteracion_valores(entorno, gamma=GAMMA, theta=THETA):
  V = np.zeros(entorno.nS)
  #obtener funcion estado - valor optima
  while True:
    delta = 0
    for s in range(entorno.nS):
      v = V[s] #almacenamos el valor anterior
      V[s] = max(calcular_funcion_q(entorno, V, s))
      delta = max(delta,abs(V[s]-v))
    if delta < theta:
      break

  politica = mejorar_politica(entorno, V)
  return politica, V

In [59]:
politica_iterVal, V_iterVal = iteracion_valores(entorno)
print('Politica optima iteracion de valores')
print(politica_iterVal)

Politica optima iteracion de valores
[[1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]


In [75]:
#interactuar con el entorno

s = entorno.reset()
for i in range(100):
  print(f'Time step: {i+1}')
  a = np.argmax(politica_iterVal[s])
  s_,r,done, info = entorno.step(a)
  s = s_
  entorno.render()
  if done:
    if s==15:
      print('El agente llego a la meta')
    else:
      print('El agente se encuentra en estado terminal')
    break
  entorno.close()

Time step: 1
  (Left)
SFFF
FHFH
FFFH
HFFG
Time step: 2
  (Left)
SFFF
FHFH
FFFH
HFFG
Time step: 3
  (Left)
SFFF
FHFH
FFFH
HFFG
Time step: 4
  (Left)
SFFF
FHFH
FFFH
HFFG
Time step: 5
  (Left)
SFFF
FHFH
FFFH
HFFG
Time step: 6
  (Left)
SFFF
FHFH
FFFH
HFFG
Time step: 7
  (Left)
SFFF
FHFH
FFFH
HFFG
Time step: 8
  (Left)
SFFF
FHFH
FFFH
HFFG
Time step: 9
  (Left)
SFFF
FHFH
FFFH
HFFG
Time step: 10
  (Left)
SFFF
FHFH
FFFH
HFFG
Time step: 11
  (Left)
SFFF
FHFH
FFFH
HFFG
Time step: 12
  (Left)
SFFF
FHFH
FFFH
HFFG
Time step: 13
  (Left)
SFFF
FHFH
FFFH
HFFG
Time step: 14
  (Left)
SFFF
FHFH
FFFH
HFFG
Time step: 15
  (Left)
SFFF
FHFH
FFFH
HFFG
Time step: 16
  (Left)
SFFF
FHFH
FFFH
HFFG
Time step: 17
  (Left)
SFFF
FHFH
FFFH
HFFG
Time step: 18
  (Left)
SFFF
FHFH
FFFH
HFFG
Time step: 19
  (Left)
SFFF
FHFH
FFFH
HFFG
Time step: 20
  (Left)
SFFF
FHFH
FFFH
HFFG
Time step: 21
  (Left)
SFFF
FHFH
FFFH
HFFG
Time step: 22
  (Left)
SFFF
FHFH
FFFH
HFFG
Time step: 23
  (Left)
SFFF
FHFH
FFFH
HFFG
Time step: 24
  (Lef

In [65]:
#evaluar la politica por episodios
def evaluar_politica_episodios(entorno, politica, episodios=100):
  exitos = 0
  for ep in range(episodios):
    s = entorno.reset()
    done = False

    while not done:
      a = np.argmax(politica[s]) #elige la accion que parezca mejor en el momento actual, segun politica
      s,r, done, _ = entorno.step(a)

      if s == 15:
        exitos += 1

  tasa_exito = exitos / episodios
  print(f'Tasa de exito en {episodios} episodios es: {tasa_exito:.2%}')
  return tasa_exito



In [79]:
evaluar_politica_episodios(entorno, politica_iterVal, episodios = 1000)

Tasa de exito en 1000 episodios es: 75.60%


0.756

In [80]:
#probar en otros entornos con espacios discretos con acciones discretas